# VALID BUT DISCOURAGED

apple.type = "fruit"
orange.type = "fruit"

apple.skin = "thin"
orange.skin = "thick"

apple.color = "red"
orange.color = "orange"

# Pair with a inline table which contains lists
pair.one = { "fl0.at-s" = [
        +1.0,
        3.1415,
        -0.01,
        5e+22,
        1e06,
        -2E-2,
        6.626e-34,
        224_617.445_991_228,
        inf,
        +inf,
        -inf,
        nan,
        +nan,
        -nan,
], 1nt_s = [
        +99,
        42,
        0,
        -17,
        1_000,
        5_349_221,
        1_2_3_4_5,
        0xDEADBEEF,
        0xdeadbeef,
        0o755,
        0b11010110,
], "d4.t3s" = [
        1979-05-27T07:32:00Z,
        1979-05-27T00:32:00-07:00,
        1979-05-27T00:32:00.999999-07:00,
        1979-05-27T07:32:00,
        1979-05-27T00:32:00.999999,
        1979-05-27,
        07:32:00,
        00:32:00.999999,
], random_string = [ "its a string" ] }

complex.booleans = [ true, false ]

complex.t = "thisisastring"

#git commit -m "Fix the lex with tokens, so that we know the state we are in."

[a-table]

"lel" = 123.2

[a-table.inside]

ip2 = "789"

[[a-table.inside.nestedArray]]
cool.abc = [[ 1, 1.2, [ "ola", "adeus" ]], "asd", 3 ]

[a-table.inside.nestedArray.primeiro]
segundo.l = "false"
segundo.bonk.l = [ 1, "'a'", [ 98, 1 ] ]


[[a-table.inside.nestedArray]]
cool.loco = 1e2
primeiro = { segundo.l = { bool ="false"}, segundo.bonk.l = [ 1, "'a'", [ 98, 1 ] ] }


[k.a.  a]
lol = 1023

[[list]]
ip = "123"

[[list]]
ip = "456"


# You can create nested arrays of tables as well.

[[fruit]]
  name = "apple"

  [fruit.physical]
    color = "red"
    shape = "round"

  [[fruit.variety]]
    name = "red delicious"

  [[fruit.variety]]
    name = "granny smith"

[[fruit]]
  name = "banana"
  [[fruit.variety]]
    name = "plantain"
