## COMMENTS

# This is a full-line comment
key = "value"  # This is a comment at the end of a line
another = "# This is not a comment"


## Key/Value Pair

key1 = "value"

#keyi = # INVALID
first = "Tom"
last = "Preston-Werner" # INVALID


## Keys

[tabela]
a=1