
1 = { terceiro = [ 1, "'a'", [ 98, 1 ] ], segundo = { bool ="false", kkk = { another = 1 }, lol = "feu" } }

3 = { segundo = { bool ="false", kkk = { another = 1 }, lol = "feu" }, terceiro = [ 1, "'a'", [ 98, 1 ] ] }

str4 = """Here are two quotation marks: "". Simple enough.""" #ennd
#str5 = """Here are three quotation marks: """."""  # INVALID
str5 = """Here are three quotation marks: ""\"."""
str6 = """Here are fifteen quotation marks: ""\"""\"""\"""\"""\"."""

# "This," she said, "is just a pointless statement."
str7 = """"This," she said, "is just a pointless statement."\  """ #nao consigo fechar com """" no fim

'q"uot"15' = '''Here are fifteen quotation marks: """""""""""""""'''

#qapos15 = '''Here are fifteen apostrophes: ''''''''''''''''''  # INVALID
apos15 = "Here are fifteen apostrophes: '''''''''''''''"

# 'That's still pointless', she said.
str = ''''That's still pointless', she said.'''