
1 = { terceiro = [ 1, "'a'", [ 98, 1 ] ], segundo = { bool ="false", kkk = { another = 1 }, lol = "feu" } }

3 = { segundo = { bool ="false", kkk = { another = 1 }, lol = "feu" }, terceiro = [ 1, "'a'", [ 98, 1 ] ] }
